/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 07:08:17 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.Stack;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class Stack_ESTest extends Stack_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      Stack stack0 = new Stack();
      stack0.push(22);
      int int0 = stack0.top();
      assertEquals(22, int0);
  }

  @Test
  public void test1()  throws Throwable  {
      Stack stack0 = new Stack();
      stack0.push(22);
      int int0 = stack0.pop();
      assertEquals(22, int0);
  }

  @Test
  public void test2()  throws Throwable  {
      Stack stack0 = new Stack();
      stack0.push((-1346));
      stack0.push((-1346));
      int int0 = stack0.top();
      assertEquals((-1346), int0);
  }

  @Test
  public void test3()  throws Throwable  {
      Stack stack0 = new Stack();
      stack0.push((-1346));
      stack0.push((-1346));
      int int0 = stack0.pop();
      assertEquals((-1346), int0);
  }

  @Test
  public void test4()  throws Throwable  {
      Stack stack0 = new Stack();
      stack0.push(0);
      int int0 = stack0.top();
      assertEquals(0, int0);
  }

  @Test
  public void test5()  throws Throwable  {
      Stack stack0 = new Stack();
      // Undeclared exception!
      try { 
        stack0.top();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Cannot pop from empty stack
         //
         assertThrownBy("edu.osu.cs362.Stack", e);
      }
  }

  @Test
  public void test6()  throws Throwable  {
      Stack stack0 = new Stack();
      stack0.push(3901);
      stack0.push(3901);
      stack0.push(3901);
      stack0.push(3901);
      stack0.push(3901);
      stack0.push(3901);
      stack0.push(3901);
      stack0.push(3901);
      stack0.push(3901);
      stack0.push(3901);
      // Undeclared exception!
      try { 
        stack0.push(3901);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Cannot add to full stack
         //
         assertThrownBy("edu.osu.cs362.Stack", e);
      }
  }

  @Test
  public void test7()  throws Throwable  {
      Stack stack0 = new Stack();
      stack0.push(0);
      int int0 = stack0.pop();
      assertEquals(0, int0);
  }

  @Test
  public void test8()  throws Throwable  {
      Stack stack0 = new Stack();
      // Undeclared exception!
      try { 
        stack0.pop();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Cannot pop from empty stack
         //
         assertThrownBy("edu.osu.cs362.Stack", e);
      }
  }
}
